# Changes here will be overwritten by Copier
_commit: v0.11.4
_src_path: https://github.com/fohte/generic-boilerplate
auto_merge_release_pr: false
description: '@fohte''s VRT report generator for reg-suit'
error_tracking: false
is_public: true
is_web_app: false
project_name: vrt-report
release_type: node
repo_id: '1386793519'
repo_language: en
storybook: false
subpackages: []
type: node
use_release_please: true
vrt: false
